import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Layout from "@/layout/Layout";
import { ChakraProvider } from '@chakra-ui/react'
import TaskProvider from "@/context/TaskProvider";
import AuthProvider from "@/context/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <ChakraProvider>
          <main className={`${styles.main} ${inter.className}`}>
            <AuthProvider session={undefined} setSession={function (value: any): void {
                          throw new Error("Function not implemented.");
                        } } register={function (data: any): void {
                          throw new Error("Function not implemented.");
                        } } login={function (data: any): void {
                          throw new Error("Function not implemented.");
                        } }
            >
              <TaskProvider task={undefined} setTask={function (value: any): void {
                            throw new Error("Function not implemented.");
                          } } getTasks={function (): void {
                            throw new Error("Function not implemented.");
                          } } createTask={function (data: any): void {
                            throw new Error("Function not implemented.");
                          } } updateTask={function (data: any): void {
                            throw new Error("Function not implemented.");
                          } } loading={false}     
              >
                <Layout />
              </TaskProvider>
            </AuthProvider>
          </main>
        </ChakraProvider>
    </>
  );
}
