import { IsSmallScreen } from '@/hooks/useDetectScreen'
import SnippetsFilled from '@ant-design/icons/SnippetsFilled'
import Head from "next/head";
import { Box, Button, FormControl, Input, Text } from '@chakra-ui/react'
import React from 'react'
import { useRouter } from 'next/router';
import { useAuth } from '@/context/AuthProvider';

const Register = () => {

  const IsSmall = IsSmallScreen()
  const router  = useRouter()
  const { register } = useAuth()
  const [user, setUser] = React.useState({ 
    username: '', 
    email: '', 
    password: '' 
  })

  const handleRouter = () => {
    router.push('/auth/login')
  }

  const handleChange = (e: any) => {
    setUser({ ...user, [e.target.name]: e.target.value })
  }

  const handleSubmit = () => {
    register(user)
  }

  return (
    <>
      <Head>
          <title>Register</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      <Box
        w='100%'
        h='100vh'
        display='flex'
        justifyContent='center'
        alignItems='center'
        bg='#111111'
        color='white'
      >
        <Box
          w={IsSmall? '90%' : '350px'}
          h='fit-content'
          display='flex'
          justifyContent='center'
          alignItems='center'
          bg='conic-gradient(from 180deg at 50% 50%, #333 0deg, #333 176deg, #61dafb 193deg, #333 217deg, #333 1turn);'
          borderRadius='11px'
          p='1px'
        >
          <Box
            w='100%'
            h='fit-content'
            p='25px 0'
            borderRadius='10px'
            display='flex'
            flexDirection='column'
            justifyContent='center'
            alignItems='center'
            gap='10px'
            bg='linear-gradient(180deg, #242424, #121212 65.62%)'
            boxShadow='0 1px 0 1px rgba(0, 0, 0, .02), 0 4px 6px rgba(0, 0, 0, .02), inset 0 0 0 6px #111'
          >
            <Box
              display='flex'
              gap='5px'
              alignItems='center'
            >
              <SnippetsFilled style={{ color: '#b8bcc4', fontSize: '24px' }} />
              <Text fontSize='20px' color='#b8bcc4' fontWeight='bold'>TaskMe</Text>
            </Box>
            <Text fontSize='20px' color='white' fontWeight='bold'>Register</Text>
            <FormControl
              w='80%'
              display='flex'
              flexDirection='column'
              gap='10px'
              color='white'
            >
              <label htmlFor="username">Username</label>
              <Input
                name='username'
                value={user.username}
                onChange={handleChange}
                placeholder='johndoe'
                border='none'
                bg='#000000'
                _placeholder={{ opacity: 1, color: '#888' }}
              />
              <label htmlFor="email">Email</label>
              <Input
                name='email'
                value={user.email}
                onChange={handleChange}
                placeholder='johndoe@gmail.com'
                border='none'
                bg='#000000'
                _placeholder={{ opacity: 1, color: '#888' }}
              />
              <label htmlFor="password">Password</label>
              <Input
                name='password'
                value={user.password}
                onChange={handleChange}
                placeholder='*********'
                type='password'
                border='none'
                bg='#000000'
                _placeholder={{ opacity: 1, color: '#888' }}
              />
              <Button
                  mt='10px'
                  onClick={handleSubmit}
              >
                Login
              </Button>
            </FormControl>
            <Box>
              <Text>{"Already have an account? "} 
                <b onClick={handleRouter} style={{cursor: 'pointer'}}>
                  Login
                </b>
              </Text>
            </Box>
          </Box>
        </Box>
      </Box>
    </>
  )
}

export default Register